### ISSUE TITLE
can I attach some data to a Card (as label or tag)

### ISSUE THREAD

**Issue by ghost** [einaregilsson/cards.js#14]
Hi,

Following your example, exactly here: 

 `discardPile.addCard(card)`*

Say for example I want to difference between two types of cards, ones comming from upperhand and ones from lowerhand.

How can I do that ? I can set order for example even and odd indexes but it would be hard because order can change in my imagination of the game.

Many thanks 👍

**Comment by ghost** [comment]
sorry for being such a stupid, just something like card.type = 0 would work; closing this.

**Comment by einaregilsson** [comment]
Not stupid at all 🙂 Glad you can use it. Which game are you making?

**Comment by ghost** [comment]
Check my [repository](https://github.com/bacloud14/Outscore-card-game). You library is just wonderful after days of literally looking anywhere ranging from Unity, Python and JavaScript. at this level, I am just making a demo about rules.

**Comment by bacloud14** [comment]
I have a question if you permit, please,
*Can I throw a Card out of the table ? from a Hand ?
I am tring this:

```
discardPile.removeCard(discardPile.topCard())
discardPile.render()
```

but iterating on some or all cards, just make them one level bellow in the appearing hand. I want to literally throw them out the table or back to the deck

thanks !
