### ISSUE TITLE
I cannot import this lib with symfony webpack encore

### ISSUE THREAD

**Issue by iatanasov77** [einaregilsson/cards.js#2]
I see browser console error:  cards.init is not a function

**Comment by einaregilsson** [comment]
I've just added an export so it should work better with bundlers. Try again, see if it works now.

**Comment by iatanasov77** [comment]
I send a pull request that fix this library to work with webpack.
but not work with CommonJs require() method.Instead use ES6 import:
`
import cards from './cards.js/cards.js';
global.cards = cards;
`
Thanks!
